name: Test and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: testdb

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run migrations
        run: npx sequelize-cli db:migrate

      - name: Run tests
        run: npm run test


  deploy:
    runs-on: ubuntu-latest
    needs: test

    env:
      POSTGRES_USER_USERS: ${{ secrets.POSTGRES_USER_USERS }}
      POSTGRES_PASSWORD_USERS: ${{ secrets.POSTGRES_PASSWORD_USERS }}
      POSTGRES_DB_USERS: ${{ secrets.POSTGRES_DB_USERS }}
      POSTGRES_PORT_USERS: ${{ secrets.POSTGRES_PORT_USERS }}
      USERS_SERVICE_PORT: ${{ secrets.USERS_SERVICE_PORT }}

      POSTGRES_USER_ORDERS: ${{ secrets.POSTGRES_USER_ORDERS }}
      POSTGRES_PASSWORD_ORDERS: ${{ secrets.POSTGRES_PASSWORD_ORDERS }}
      POSTGRES_DB_ORDERS: ${{ secrets.POSTGRES_DB_ORDERS }}
      POSTGRES_PORT_ORDERS: ${{ secrets.POSTGRES_PORT_ORDERS }}
      ORDERS_SERVICE_PORT: ${{ secrets.ORDERS_SERVICE_PORT }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy na EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/microsservicos
            git pull
            docker-compose down
            docker-compose up --build -d
          EOF
